spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver

jpa:
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081

h2:
  console:
    enabled: true
